version: '3.8'

services:
  backend:
    build:
      context: .
    platform: linux
    image: serikaron/blockchain-web
    volumes:
      - ./config.json:/src/config.json
    entrypoint: node --experimental-json-modules /src/main.js
    ports:
      - "8000:8080"